### ISSUE TITLE
Having different rhythms for different device classes

### ISSUE THREAD

**Issue by custa1200** [sakamies/postcss-gridlover#4]
If the variables are defined on root, how would would go about having a separate rhythm for desktop and mobile devices?

**Comment by sakamies** [comment]
Right now there's no way to do separate rhytms. It should be possibble to change any gridlover variable at any time but I haven't had the time to implement it yet. Thanks for the input!

**Comment by sakamies** [comment]
You can now define base variables at any point in the css. Everything below a base variable uses that variable, so it doesn't yet follow the cascade.
